version: "3"
services:
  mongo:
    image: mongo:6.0
    container_name: travel-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: travel
    volumes:
      - ./mongo-data:/data/db

  backend:
    image: marijaklisarovska/travel-backend:latest
    container_name: travel-backend
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/travel

  frontend:
    image: marijaklisarovska/travel-frontend:latest
    container_name: travel-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


#version: "3"
#services:
#  travel-db:
#    image: "postgres"
#    container_name: "travel"
#    environment:
#      - POSTGRES_USER=mila
#      - POSTGRES_PASSWORD=wp123
#      - POSTGRES_DB=travel
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#version: '3.9'
#
#services:
#  postgres:
#    image: postgres:14-alpine
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: sara
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#volumes:
#  postgres-data:
#    driver: local