apiVersion: v1
kind: ConfigMap
metadata:
  name: travel-backend-config
  namespace: travel-app
data:
  application.properties: |
    spring.application.name=TravelService
    security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    security.jwt.expiration-time=3600000
    openai.api.key=sk-8vACYkBjUPTfp_yNV6_gty_T0O_9BBT15lu4U90aUST3BlbkFJEKUy0pdzPFpOkN2PrkhOMUMS2Zr_QOInXQCPK5xk8A
    spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    spring.data.mongodb.uri=mongodb://root:dbpass4@mongo.travel-app.svc.cluster.local:27017/travelapp?authSource=admin
