apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-ingress
  namespace: travel-app
spec:
  rules:
    - host: travel.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: travel-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: travel-frontend
                port:
                  number: 80